### ISSUE TITLE
Adding icon to a Button's properties breaks it's active highlighting

### ISSUE THREAD

**Issue by ggascoigne** [Tripwire/octagon#59]
If I add the icon property to this button:

```js
              <Button
                icon
                className='tripwire'>
                Example
                <Icon name='plus' style={{paddingLeft: '0.5em'}} />
              </Button>
```

then the :active css style is no longer applied.  Removing it re-actives the :active style but lays the icon out incorrectly.

**Comment by ggascoigne** [comment]
a fix seems to be apply this css:

```css
.ui.icon.button:active {
  border-color: #3498db;
  color: #FFFFFF;
  background: #3498db;
}
```
Not sure if this is the best fix though.
